### ISSUE TITLE
Git not coresponding with vmchecker

### ISSUE THREAD

**Issue by buzicaandrei12** [alexandruradovici/alf2018#21]
Hello. The tests on git have been modified. Can you please update the checker ?

**Comment by alexandruradovici** [comment]
Fixed

**Comment by alexandruradovici** [comment]
Fixed, bonus should be available now.

**Comment by buzicaandrei12** [comment]
No it's not fixed.  On vm checker the variables still don't have the attribute value...
